version: '1.0'

services:

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env # Temporary

  frontend:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

