version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env # Temporary
    volumes:
        - ./server:/app/server
        - ./repository:/app/repository

  frontend:
    build:
      context: .
      dockerfile: ui/Dockerfile
    image: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
