name: Docker Compose CI

on: [pull_request]

jobs:
  compose_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Need to configure default .env variables and localstack emulation 

    # - name: Build and run Docker Compose
    #   run: |
    #     docker-compose up --build -d

    # - name: Check running server
    #   run: |
    #     docker-compose ps
    #     if [[ $(docker-compose ps | grep 'server') ]]; then
    #         echo "FastAPI service is up."
    #     else
    #         echo "FastAPI failed to run."
    #         exit 1
    #     fi

    # - name: Check running ui
    #   run: |
    #     docker-compose ps
    #     if [[ $(docker-compose ps | grep 'ui') ]]; then
    #         echo "React app is up."
    #     else
    #         echo "React app failed to run."
    #         exit 1
    #     fi