name: Server CI

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'server/**'
      - 'repository/**'

      
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'backend/**'

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    # Backend specific CI steps...
