name: UI CI

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'ui/**'
      - 'repository/feature_store.yaml'

  pull_request:
    branches: [ main, dev ]
    paths:
      - 'ui/**'
      - 'repository/feature_store.yaml'

jobs:
  build-and-test-ui:
    runs-on: ubuntu-latest
    # UI specific CI steps...
