name: UI CD

on:
  push:
    branches: [ main ]
    paths:
      - 'ui/**'

jobs:
  deploy-ui:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: TBD
      run: |
        # UI specific CD steps...