name: UI CI

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'ui/**'
      - 'repository/feature_store.yaml'

  pull_request:
    branches: [ main, dev ]
    paths:
      - 'ui/**'
      - 'repository/feature_store.yaml'

jobs:
  build-and-test-ui:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: TBD
      run: |
        # UI specific CD steps...